---
glob: "**/*.html{+*,}.erb"
exclude:
  - "**/vendor/**/*"
linters:
  AllowedScriptType:
    enabled: true
  ClosingErbTagIndent:
    enabled: true
  CommentSyntax:
    enabled: true
  ErbSafety:
    enabled: true
  ExtraNewline:
    enabled: true
  FinalNewline:
    enabled: true
  NoJavascriptTagHelper:
    enabled: true
  ParserErrors:
    enabled: true
  RequireInputAutocomplete:
    enabled: false
  RightTrim:
    enabled: true
  SelfClosingTag:
    enabled: true
  SpaceAroundErbTag:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
  SpaceIndentation:
    enabled: true
  TrailingWhitespace:
    enabled: true
