default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
      # fast lane
    # - queues: "latency_10s"
    #   threads: 8
    #   processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
    #   polling_interval: 0.1
    #   # middle lane
    # - queues: "latency_10s,latency_5m"
    #   threads: 5
    #   processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
    #   polling_interval: 0.1
    #   # slow lane
    - queues: "latency_10s,latency_5m,literally_whenever,default,*"
      threads: 16
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
